### ISSUE TITLE
вьюха index

### ISSUE THREAD

**Issue by maximon93** [DartVadius/rocketapp#3]
for blog_post in blog_posts:
        if re.search('(<img .* />)', blog_post.short_text):
            images[blog_post.id] = re.search('(<img .* />)', blog_post.short_text).group(1)
        else:
            images[blog_post.id] = '<img alt="" src="/static/img/dummies/t1.jpg" />'

это такая лють, и порождает лють в темплейте

Подумай, может с помощью джанго можно красивее и лаконичнее это сделать

**Comment by DartVadius** [comment]
fix
